// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBot891YBrtHrvW160xoB0BSWKHJKPsd8w',
    appId: '1:1055801229936:web:ac2934f6c8fe7af8796ab5',
    messagingSenderId: '1055801229936',
    projectId: 'flutternotes-461e3',
    authDomain: 'flutternotes-461e3.firebaseapp.com',
    storageBucket: 'flutternotes-461e3.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBe9s9EHsepQYG9-I6qNkNzGjAjqz710ds',
    appId: '1:1055801229936:android:96e6161a67f00cac796ab5',
    messagingSenderId: '1055801229936',
    projectId: 'flutternotes-461e3',
    storageBucket: 'flutternotes-461e3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAA7RhVgNHx9Xa9SyAE8hM9fDb4_wLGkdQ',
    appId: '1:1055801229936:ios:2505dc7b691291d9796ab5',
    messagingSenderId: '1055801229936',
    projectId: 'flutternotes-461e3',
    storageBucket: 'flutternotes-461e3.appspot.com',
    iosBundleId: 'com.example.flutterNotes',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBot891YBrtHrvW160xoB0BSWKHJKPsd8w',
    appId: '1:1055801229936:web:85a78401331ade13796ab5',
    messagingSenderId: '1055801229936',
    projectId: 'flutternotes-461e3',
    authDomain: 'flutternotes-461e3.firebaseapp.com',
    storageBucket: 'flutternotes-461e3.appspot.com',
  );
}
